### ISSUE TITLE
好像销毁的代码没有调整

### ISSUE THREAD

**Issue by qcjxberin** [NewLifeX/NewLife.MQ#1]
好像销毁的代码没有调整

**Comment by nnhy** [comment]
更新组件到1109 · NewLifeX/NewLife.MQ@9c0a28a
https://github.com/NewLifeX/NewLife.MQ/commit/9c0a28afd5964e2b0437986b917f74b53ff9df8e

**Comment by qcjxberin** [comment]
给力
